baseURL = "http://komi.dev"
languageCode = "en-us"
title = "Launch Today"
theme = "hugo-theme-cleanwhite"
preserveTaxonomyNames = true
paginate = 5
googleAnalytics = "UA-177061519-1"
hasCJKLanguage = true

[outputs]
home = ["html", "rss", "json"]

[params]
  header_image = "img/home.jpg"
  SEOTitle = "Yusuke Kominami"
  description = "Yusuke Kominami's Blog. About software engineering, career, lifestyle."
  keyword = "Yusuke Kominami, 小南佑介, 小南 佑介, Rust, Emacs, Lisp, Web, Machine Learning, 機械学習"
  slogan = "Playground and Workspace for Awesome Ideas"

  title = "Launch Today"
  thumbnail = "img/home.jpg"

  image_404 = "img/404-bg.jpg"
  title_404 = "Page Not Found :("
  omit_categories = false

  algolia_search = true

  # Sidebar settings
  sidebar_about_description = "Software Developer, Rustacean, Open Source Enthusiast"
  sidebar_avatar = "img/me.jpg"

  featured_tags = true
  featured_condition_size = 1
  
  about_me = true

  [params.social]
    rss = true
    email = "yusuke.kominami@gmail.com"
    twitter = "https://twitter.com/komi_edtr_1230"
    github = "https://github.com/komi1230"
    facebook = "https://www.facebook.com/1230komi/"
    linkedin = "https://www.linkedin.com/in/yusuke-kominami-0419b1157/"
    stackoverflow = "https://stackoverflow.com/users/12464570"

  [[params.addtional_menus]]
    title =  "ABOUT"
    href =  "/top/about/"

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "emacs"
